server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    hibernate:
      #更新或创建数据库表结构
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**